management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        mongodb.driver.commands: true
        cache.gets: true
        resilience4j.circuitbreaker: true
    tags:
      application: ${spring.application.name}

spring:
  swagger-ui:
    customCssUrl: /swagger-ui/custom.css
  mongodb:
    host: localhost
    port: 27017
    database: url_shortener
    username: root
    password: root
    authentication-database: admin
  application:
    name: read-api
  security:
    exp:
      token: 24
      refresh: 444444
    jwt:
      secret: 5438y43v734vb7t40yt7y7rft47r7tv43htf3ht40f7t430ft0ft3t4fh94t3r3653667586578784658467867846786667v
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: url-shortener-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

resilience4j:
  retry:
    instances:
      database:
        max-attempts: 4
        wait-duration: 300ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 3
        retry-exceptions:
          - com.read.api.domain.exceptions.TransientDatabaseException
        ignore-exceptions:
          - org.springframework.dao.DataIntegrityViolationException
          - java.lang.IllegalStateException
      kafka:
        timeout-duration: 5s
        max-attempts: 4
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 4
        retry-exceptions:
          - org.apache.kafka.common.errors.RetriableException
          - org.springframework.kafka.KafkaException

  circuitbreaker:
    instances:
      kafka:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

  bulkhead:
    instances:
      kafka:
        max-concurrent-calls: 10
        max-wait-duration: 0
      outbox:
        max-concurrent-calls: 2
        max-wait-duration: 0

  timelimiter:
    instances:
      kafka:
        timeout-duration: 2s

  ratelimiter:
    instances:
      read-low:
        limit-for-period: 100
        limit-refresh-period: 4s
        timeout-duration: 0
      read-middle:
        limit-for-period: 120
        limit-refresh-period: 3s
        timeout-duration: 0
      read-strong:
        limit-for-period: 180
        limit-refresh-period: 2s
        timeout-duration: 0

app:
  http:
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "https://meuapp.com"
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed-headers:
        - "*"
      allow-credentials: true