spring:
  datasource:
    url: jdbc:mysql://localhost:4000/url_shortener
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      enabled: true

  threads:
    virtual:
      enabled: true

  application:
    name: demo
