management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: [ w3c, b3 ]
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    enable:
      http: true
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
logging:
  file:
    name: logs/app.log
  pattern:
    level: "%5p [demo,%X{traceId:-},%X{spanId:-}]"
  level:
    com.write.api: DEBUG
    org.springframework.web: DEBUG
    io.micrometer: DEBUG

resilience4j:
  retry:
    instances:
      database:
        max-attempts: 3
        wait-duration: 300ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 3
        retry-exceptions:
          - com.write.api.core.domain.exception.TransientDatabaseException
        ignore-exceptions:
          - org.springframework.dao.DataIntegrityViolationException
          - java.lang.IllegalStateException
      kafka:
        timeout-duration: 5s
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 4
        retry-exceptions:
          - org.apache.kafka.common.errors.RetriableException
          - org.springframework.kafka.KafkaException

  circuitbreaker:
    instances:
      kafka:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

  bulkhead:
    instances:
      kafka:
        max-concurrent-calls: 10
        max-wait-duration: 0
      outbox:
        max-concurrent-calls: 2
        max-wait-duration: 0

  timelimiter:
    instances:
      kafka:
        timeout-duration: 2s

  ratelimiter:
    instances:
      create:
        limit-for-period: 100
        limit-refresh-period: 2s
        timeout-duration: 0
      create-internal:
        limit-for-period: 120
        limit-refresh-period: 2s
        timeout-duration: 0
      login:
        limit-for-period: 90
        limit-refresh-period: 2s
        timeout-duration: 0
      logout:
        limit-for-period: 70
        limit-refresh-period: 2s
        timeout-duration: 0
      refresh-token:
        limit-for-period: 120
        limit-refresh-period: 2s
        timeout-duration: 0
      test:
        limit-for-period: 30
        limit-refresh-period: 10s
        timeout-duration: 0
      delete:
        limit-for-period: 110
        limit-refresh-period: 4s
        timeout-duration: 0
      update:
        limit-for-period: 50
        limit-refresh-period: 4s
        timeout-duration: 0

spring:
  application:
    name: demo
  super-adm:
    name: superadm
    email: superadm@gmail.com
    password: 12345678
  security:
    exp:
      token: 24
      refresh: 444444
    jwt:
      secret: 5438y43v734vb7t40yt7y7rft47r7tv43htf3ht40f7t430ft0ft3t4fh94t3r3653667586578784658467867846786667v
  datasource:
    url: jdbc:mysql://localhost:4000/url_shortener
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: UrlShortenerPool
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 30000
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: url-shortener-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

app:
  http:
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "https://meuapp.com"
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed-headers:
        - "*"
      allow-credentials: true

server:
  port: 8080